apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-agent-cluster-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-agent-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: devops-tools
roleRef:
  kind: ClusterRole
  name: jenkins-agent-cluster-admin
  apiGroup: rbac.authorization.k8s.io